# fly.toml app configuration file generated for node-react on 2023-09-23T20:15:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-react"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
